base_url = "https://nicholasruddick.com"
title = "Hallo"

compile_sass = false

highlight_code = false

build_search_index = false

[extra]
greeting = "Hello!"

iam = "I am"

links = [
    { title = "E-Mail", url = "mailto:mail@example.org", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com", icon = "github" },
    { title = "Twitter", url = "https://twitter.com", icon = "twitter" },
    { title = "LinkedIn", url = "https://www.linkedin.com", icon = "linkedin" },
    { title = "Keybase", url = "https://keybase.io", icon = "keybase" }
]

[extra.author]
name = "Hallo"

[extra.theme]
background = "#6FCDBD"
foreground = "#FFF"
hover = "#333"
